# Generated by Django 4.1.2 on 2025-04-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_emission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_country',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='income_group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
